version: "3.8"

services:

  database:
    image: mongo:7
    container_name: database

  backend:
    build: ./backend
    container_name: backend

    ports:
      - "5000:5000"

    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: frontend

    ports:
      - "80:80"

    depends_on:
      - backend