apiVersion: v1
kind: Pod
metadata:
  name: my-frontend-test2-pod
  labels:
    project: fullstack-test2
    app: frontend
spec:
  containers:
    - name: test2-container-f
      image: richards7/frontend:4
      ports:
        - containerPort: 80